# Generated by Django 4.2.2 on 2023-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Message', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
