# Generated by Django 4.2.2 on 2023-06-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name_surname',
        ),
    ]
