# Generated by Django 4.2.2 on 2023-10-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_name_contact_name_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectimg', models.ImageField(upload_to='')),
                ('protitle', models.CharField(max_length=30)),
                ('prodescrip', models.CharField(max_length=400)),
            ],
        ),
    ]
